<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <VersionPrefix>4.1.2</VersionPrefix>
    <Version>4.1.2</Version>
    <AssemblyVersion>4.1.2.0</AssemblyVersion>
    <FileVersion>4.1.2.0</FileVersion>
    <InformationalVersion>4.1.2 Developer Preview</InformationalVersion>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
